// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Ll6SyAvsBEVyUoM-L9QB1Ipv4HrvAr4',
    appId: '1:505870272175:web:2ee6ff935e499b6505765a',
    messagingSenderId: '505870272175',
    projectId: 'test-cli-af330',
    authDomain: 'test-cli-af330.firebaseapp.com',
    storageBucket: 'test-cli-af330.firebasestorage.app',
    measurementId: 'G-J9YLDMJ42H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZPlP4mdtmO7oebASGFlD0rJ_2Nn2N9TU',
    appId: '1:505870272175:android:caeeb394892ccb7005765a',
    messagingSenderId: '505870272175',
    projectId: 'test-cli-af330',
    storageBucket: 'test-cli-af330.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGBBc-FALiCeWN8BPetRvYBCQ9IchDfZU',
    appId: '1:505870272175:ios:a91e56ef544ca99105765a',
    messagingSenderId: '505870272175',
    projectId: 'test-cli-af330',
    storageBucket: 'test-cli-af330.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGBBc-FALiCeWN8BPetRvYBCQ9IchDfZU',
    appId: '1:505870272175:ios:a91e56ef544ca99105765a',
    messagingSenderId: '505870272175',
    projectId: 'test-cli-af330',
    storageBucket: 'test-cli-af330.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Ll6SyAvsBEVyUoM-L9QB1Ipv4HrvAr4',
    appId: '1:505870272175:web:9b9f58284f9bc4cb05765a',
    messagingSenderId: '505870272175',
    projectId: 'test-cli-af330',
    authDomain: 'test-cli-af330.firebaseapp.com',
    storageBucket: 'test-cli-af330.firebasestorage.app',
    measurementId: 'G-3TYX14VPP3',
  );
}
